version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore Capibara.PCL.sln -Verbosity quiet
- ps: choco install codecov --no-progress
environment:
  TWITTER_CONSUMER_KEY: foobar
  TWITTER_CONSUMER_SECRET_KEY: foobar
build:
  project: Capibara.PCL.sln
  verbosity: quiet
after_build:
- ps:
before_test:
- ps:
test_script:
- ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../capibara.core.coverage.xml' /p:Include="[Capibara.Core]*" Capibara.Test.Core/Capibara.Test.Core.csproj
- ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../capibara.domain.coverage.xml' /p:Include="[Capibara.Domain]*" Capibara.Test.Domain/Capibara.Test.Domain.csproj
- ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../capibara.presentation.coverage.xml' /p:Include="[Capibara.Presentation]*" Capibara.Test.Presentation/Capibara.Test.Presentation.csproj
after_test:
- ps: >-
    $coveragefiles = (Get-ChildItem -Path "*.coverage.xml").Name

    codecov -v -f $coveragefiles