version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore Capibara.PCL.sln
- ps: choco install opencover.portable
- ps: choco install codecov
environment:
  TWITTER_CONSUMER_KEY: foobar
  TWITTER_CONSUMER_SECRET_KEY: foobar
build:
  project: Capibara.PCL.sln
  verbosity: quiet
after_build:
- ps:
before_test:
- ps:
test_script:
- ps: dotnet test Capibara.Test/Capibara.Test.csproj /p:CollectCoverage=true /p:Exclude=\"[Capibara.DataProviders]Capibara.Net.ChannelCableFactory,[Capibara.DataProviders]Capibara.Net.ChannelFactory,[Capibara.DataProviders]Capibara.Net.RequestFactory*,[Capibara.DataProviders]Capibara.Net.WebSocket*,[Capibara.DataProviders]Capibara.Models.Error,[Capibara.DataProviders]Capibara.Models.RoomComparer,[Capibara]Capibara.Behaviors.*,[Capibara]Capibara.Effects.*,[Capibara]Capibara.Ioc.*,[Capibara]Capibara.Forms.*,[Capibara]Capibara.Views.*,[Capibara]Capibara.Selectors.*,[Capibara]Capibara.App*,[Capibara]Capibara.Environment*,[Capibara]Capibara.IContainerProviderExtensions,[Capibara]Capibara.ImageSourceExtensions\" /p:CoverletOutputFormat=opencover /p:CoverletOutput='../coverage.xml'
after_test:
- ps: codecov -f "coverage.xml"