version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore Capibara.PCL.sln -Verbosity quiet
- ps: choco install codecov --no-progress
- ps: choco install opencover --no-progress
environment:
  TWITTER_CONSUMER_KEY: foobar
  TWITTER_CONSUMER_SECRET_KEY: foobar
build:
  project: Capibara.PCL.sln
  verbosity: quiet
after_build:
- ps:
before_test:
- ps:
test_script:
- ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../coverage.xml' /p:Exclude=\"[Capibara.Domain.Fixture]*%2c[Capibara.Presentation]Capibara.Presentation.Views.*\" Capibara.Test/Capibara.Test.csproj
after_test:
- ps: codecov -f './coverage.xml'